ShopBook/src/ShopBook/Components/BannerViewComponent.cs
using System.Linq;
using ShopBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace ShopBook.Components
{
    public class BannerViewComponent: ViewComponent
    {
        private IProductRepository repository;
        public BannerViewComponent(IProductRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x));
        }
    }
}

ShopBook/src/ShopBook/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShopBook.Models;

namespace ShopBook.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

ShopBook/src/ShopBook/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShopBook.Infrastructure;
using ShopBook.Models;
using ShopBook.Models.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ShopBook.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private Cart cart;
        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToActionResult RemoveFromCart(int productId,
        string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

ShopBook/src/ShopBook/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopBook.Models;
using ShopBook.Models.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ShopBook.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 4;
        public ProductController(IProductRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category, int page = 1)
            => View(new ProductsListViewModel
            {
                Products = repository.Products
            .Where(p => category == null || p.Category == category)
            .OrderBy(p => p.ProductID)
            .Skip((page - 1) * PageSize)
            .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                        repository.Products.Count() :
                        repository.Products.Where(e =>
                        e.Category == category).Count()
                },
                CurrentCategory = category
            });

        public ViewResult Sreach(string category, int page = 1) => View(new ProductsListViewModel
        {
            Products = repository.Products
            .Where(p => category == null || p.Name.Contains(category))
            .OrderBy(p => p.ProductID)
            .Skip((page - 1) * PageSize)
            .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = PageSize,
                TotalItems = category == null ?
                        repository.Products.Count() :
                        repository.Products.Where(e =>
                        e.Category == category).Count()
            },
            CurrentCategory = category
        });
    }
}

ShopBook/src/ShopBook/Views/Shared/Index.cshtml
@model IEnumerable<Product>
@foreach (var p in Model)
{
    <div>
        <h3>@p.Name</h3>
        @p.Description
        <h4>@p.Price.ToString("c")</h4>
    </div>
}

ShopBook/src/ShopBook/Views/Shared/ProductSummary.cshtml
@model Product
<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">
            @Model.Price.ToString("c")
            
        </span>
    </h3>
    
    <form id="@Model.ProductID" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <span><img style="width:50%" src="~/images/@Model.files" /></span>
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <div></div>
        <span class="lead">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" >
                Add To Cart
            </button> 
        </span>
    </form>
</div>
<div class="well-lg"></div>

ShopBook/src/ShopBook/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script asp-src-include="lib/jquery/**/jquery.min.js"></script>
    <script asp-src-include="lib/jquery-validation/**/jquery.validate.min.js">
    </script>
    <script asp-src-include="lib/jquery-validation-unobtrusive/**/*.min.js"></script>
</head>
<body class="panel panel-default">
    <div class="panel-heading">
        <h4>
            @ViewBag.Title
            <a class="btn btn-sm btn-primary pull-right"
               asp-action="Logout" asp-controller="Account">Log Out</a>
        </h4>
    </div>
    <div class="panel-body">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

ShopBook/src/ShopBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
    <title>Shop Book</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation" style="width:100%">
        <a class="navbar-brand" style="width:20%" href="#">SHOP BOOK</a>
        <div class="pull-right" style="width:50px">
            @await Component.InvokeAsync("CartSummary")
        </div>
        <form method="get" asp-action="Sreach" asp-controller="Product">
            <div class="pull-right" style="color:white;width:60%;margin-top:8px">
                <span style="width:5%;float:right">&nbsp;</span>
                <span style="width:50px;float:right">
                    <input type="button" class="form-control" value="GO">
                </span>
                <input type="text" class="form-control " name="category" id="category" placeholder="Search for..." style="width:30%;float:right">
            </div>
        </form>
        @*@using (Html.BeginForm("Sreach", "Product", FormMethod.Get))
        {
            <p>
                Title: @Html.TextBox("category") <br />
                <input type="submit" value="Filter" />
            </p>
        }*@
    </div>
    <div class="col-lg-12 bg-info">
        @await Component.InvokeAsync("Banner")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>